# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '3.7'
networks:
  monitoring:
    name: monitoring

services:

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.config.file=/etc/prometheus/web-config.yml'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    volumes:
      - ./prometheus/config:/etc/prometheus
    ports:
      - 9090:9090 #interface web
  
  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/config/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'

  grafana:
    image: grafana/grafana:10.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana

  node_exporter:
    image: prom/node-exporter
    container_name: node_exporter
    command:
      - "--path.rootfs=/hostfs"
    ports:
      - 9101:9100
    restart: always
    volumes:
      - "/:/hostfs"
    networks:
      - monitoring

  exporter:
    image: besu-rpc-exporter 
    container_name: besu_rpc_exporter
    ports:
      - "8000:8000"
    environment:
      - NODE_URL=http://192.168.18.10:8545
    restart: unless-stopped
    networks:
      - monitoring
volumes:
  grafana-storage:
