{
 "title": "Besu Clean Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "Instance", "query": "label_values(up, instance)" }
  ]
 },
 "panels": [
  {
   "title": "Peers Conectados",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "besu_rpc_peer_count", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Peers Desconectados",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(besu_peers_connected_total{node=\"node1\"})- count(ethereum_peer_count)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Contagem de Peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(ethereum_peer_count)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Block Number",
   "type": "stat",
   "description": "Número do Bloco Atual",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "besu_rpc_block_number", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cpu) (rate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Validadores Ativos",
   "type": "stat",
   "description": "Validadores Ativos",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(besu_rpc_block_proposer) by (proposer)",
     "legendFormat": "{{proposer}}"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Transações por Bloco",
   "type": "timeseries",
   "description": "Tx por Bloco",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "besu_rpc_block_txcount", "legendFormat": "{{block}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Limite de Peers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ethereum_peer_limit", "legendFormat": "{{node}}" }
   ]
  }
 ]
}